stages:
  - build
  - test

variables:
  GO111MODULE: "on"

before_script:
  - go mod download

build:
  stage: build
  script:
    - go build -o myapp
  tags:
    - golang

test:
  stage: test
  script:
    - go test -v ./...
  tags:
    - golang
