stages:
  - build
  - test

variables:
  GO111MODULE: "on"

before_script:
  - go mod download

build:
  stage: build
  script:
    - make build
  tags:
    - golang

test:
  stage: test
  script:
    - make test
  tags:
    - golang
